### PR TITLE
fix: HTTP_PORT environment variable update to differentiate container and external app ports

### PR DESCRIPTION
**Pull request by colfax23**
Hello!  I ran into an issue passing in a new value for `HTTP_PORT` and I'm proposing a fix for it.  Let me know what you think, I'm happy to iterate on it.  This tool is great, thanks for all of your work.

## The Issue

I had a conflict on my server at port `8080` so I passed in a new value to `HTTP_PORT` and the tool would not function properly. I identified the root cause of the issue to be that the `HTTP_PORT` environment variable is referenced everywhere the app's http port is needed, except for one place, in the [prometheus.yml](https://github.com/lidofinance/ethereum-validators-monitoring/blob/develop/docker/prometheus/prometheus.yml#L26) file.

## The Fix

I did some digging to see if we could easily pass the environment variable into that file, and this appears to be a [known limitation](https://github.com/prometheus/prometheus/issues/2357) for which there is no simple workaround.

I recognized that this HTTP_PORT is being used both for the internal container port, as well as the one that's exposed externally to the host.  Separating them out to two different variables allows the user to specify a different external port while keeping the container port the same (thus, no need to update it for prometheus).  In my case, I only need to update the exposed port, not the internal port for the container.

1. I've replaced the environment variable `HTTP_PORT` with both `APP_CONTAINER_HTTP_PORT` for the port on the container and `APP_EXTERNAL_HTTP_PORT` for the port exposed externally to the host.
2. I also noticed that `HTTP_PORT` is actually a mandatory parameter (it is referenced in the compose file, before the default value is set in `env.validation.ts`), so I made both of the above parameters mandatory.
3. Since there is no simple way to have `docker/prometheus/prometheus.yml` read the ENV variable, I added a note to the `APP_CONTAINER_HTTP_PORT` variable description in the README mentioning that updates need to happen in `prometheus.yml` too.

## Testing

I've tested the following scenarios:
- Setting the same value for `APP_CONTAINER_HTTP_PORT` and `APP_EXTERNAL_HTTP_PORT` in the `.env` file.
- Setting different values for `APP_CONTAINER_HTTP_PORT` and `APP_EXTERNAL_HTTP_PORT` in the `.env` file.
- Setting the same value for `APP_CONTAINER_HTTP_PORT` in `.env` and the `ethereum-validators-monitoring` target in `docker/prometheus/prometheus.yml`.
- Setting different values for `APP_CONTAINER_HTTP_PORT` in `.env` and the `ethereum-validators-monitoring` target in `docker/prometheus/prometheus.yml` - this does *not* work, as expected.

## Alternatives
- We can hard code the `APP_CONTAINER_HTTP_PORT`, and only allow the user to specify the `APP_EXTERNAL_HTTP_PORT`.
- We can dynamically create the `prometheus.yml` file based on a template at compose time, but that introduces more complexity.

### CODE REVIEW

**Comment by vgorkavenko** [comment]
Hello @colfax23 ! Thank you for contribution!
I think the main issue with ports is networking on your host, and it should be solved by properly configuring the docker, host and compose file. I'm not sure if the problem should be solved by changes in the application.
If you write more details about your case, I will try to help you with config!

**Comment by colfax23** [comment]
Hey @vgorkavenko !  Thanks for taking a look.  I was able to get the config sorted out to get everything up on my machine, I appreciate the offer to help though.

The motivation for the PR is that despite any particular configurations on my machine, based on my testing the `HTTP_PORT` environment variable does not work properly and the system fails if someone passes in any value besides 8080 to it (without also changing it in `prometheus.yml`).  I could be mistaken though, have you been able to get this to work?

**Comment by vgorkavenko** [comment]
@colfax23 I think it can be solved like this

### .env
```yaml
HTTP_PORT=8080
EXTERNAL_HTTP_PORT=8099
```
### docker-compose.yml
```yaml
    ...
    expose:
      - "${HTTP_PORT}"
    ports:
      - "${EXTERNAL_HTTP_PORT}:${HTTP_PORT}"
    ...
```
Thus, no changes to the app source code are required
Definitely, it should be fixed in repo and there should be note in README about this.

So, I suggest you bring this changes to `.env.example` and `docker-compose.yml`. And a note in `README` about the effect of changing the value of `HTTP_PORT` as well

**Comment by colfax23** [comment]
Thanks @vgorkavenko , makes sense. I'm working on this, I'll update this PR when I'm done!

**Comment by colfax23** [comment]
Updated!  I left `EXTERNAL_HTTP_PORT` commented out in the `.env.example` and I made it so that the default behavior is still to use `HTTP_PORT` if `EXTERNAL_HTTP_PORT` is not specified.  Thanks for the tip and happy to iterate on it again if you'd like.

**Pull request merged**
